// <auto-generated />
namespace Ders32_CodeFirst_Linq.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ilkolusum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ilkolusum));
        
        string IMigrationMetadata.Id
        {
            get { return "202301221050253_ilkolusum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
